
DROP SCHEMA IF EXISTS `revionics`;

CREATE SCHEMA `revionics`;
USE `revionics` ;

CREATE TABLE IF NOT EXISTS `revionics`.`LOGINTEST` (
  `USERID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(255) NULL DEFAULT NULL,
 
    `PASSWORD` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`USERID`))
;
